---
# Kubernetes 集群主机清单（YAML 格式）
# 根据实际情况修改 IP 地址和主机名

all:
  hosts:
    localhost:
      ansible_connection: local
  children:
    etcd:
      hosts:
        # etcd 集群节点（通常为奇数个，建议3个或5个）
        etcd1:
          ansible_host: 192.168.0.112
          etcd_hostname: 'etcd01.k8s.local'
        etcd2:
          ansible_host: 192.168.0.113
          etcd_hostname: 'etcd02.k8s.local'
        etcd3:
          ansible_host: 192.168.0.114
          etcd_hostname: 'etcd03.k8s.local'

    masters:
      hosts:
        # Kubernetes Master 节点
        master1:
          ansible_host: 192.168.0.112
          hostname: 'master01.k8s.local'
          etcd_hostname: 'etcd01.k8s.local'
        master2:
          ansible_host: 192.168.0.113
          hostname: 'master02.k8s.local'
          etcd_hostname: 'etcd02.k8s.local'
        master3:
          ansible_host: 192.168.0.114
          hostname: 'master03.k8s.local'
          etcd_hostname: 'etcd03.k8s.local'

    workers:
      hosts:
        # Kubernetes Worker 节点
        # worker1:
        #   ansible_host: 192.168.1.30
        # worker2:
        #   ansible_host: 192.168.1.31
        # worker3:
        #   ansible_host: 192.168.1.32

    # 逻辑分组（示例，通常用于 play 中指定 hosts）
    kube-master:
      children:
        masters:

    kube-node:
      children:
        workers:

    k8s-cluster:
      children:
        masters:
        workers:

  vars:
    # 全局变量
    ansible_ssh_user: root
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    # etcd 集群主机名配置（全局可用）
    etcd01_hostname: 'etcd01.k8s.local'
    etcd02_hostname: 'etcd02.k8s.local'
    etcd03_hostname: 'etcd03.k8s.local'
    master01_hostname: 'master01.k8s.local'
    master02_hostname: 'master02.k8s.local'
    master03_hostname: 'master03.k8s.local'